# Generated by Django 3.0.4 on 2020-03-26 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recyclerApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainusers',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='mainusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mainusers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='mainusers',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='email',
            field=models.EmailField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='full_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='password',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainusers',
            name='user_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
